apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: data
          mountPath: /mosquitto/data/
        ports:
        - containerPort: 1883
        - containerPort: 9001 
      volumes:
      - name: config
        configMap:
          name: config
      - name: data
        persistentVolumeClaim:
          claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
spec:
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
    protocol: TCP
  - port: 9001
    targetPort: 9001
    name: mqtt-websocket
    protocol: TCP
  type: LoadBalancer
  selector:
    app: mosquitto
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
